apiVersion: skaffold/v2beta28
kind: Config
build:
  artifacts:
    - image: backend-image
      context: backend
    - image: frontend-image
      context: frontend
deploy:
  kubectl:
    manifests:
      - k8s/*.yaml
portForward:
  - resourceType: service
    resourceName: frontend-service
    port: 80
    localPort: 8080

